FROM nginx
WORKDIR /app

# cartella delle configurazioni
COPY ./config/nginx/ /etc/nginx/conf.d/

# cartelle del sito
COPY ./app/dist/app/browser /app 

EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]