version: "3.9"

networks:
  cert-auth-net:

##########################################
secrets: {}


##########################################
volumes:
  pki:

##########################################
services:

  api:
    container_name: certauth-api
    build:
      context: ./
      dockerfile: Dockerfile.api-dev
    restart: unless-stopped
    environment:
      MODE: DEVELOPMENT
      PYTHONUNBUFFERED: 1
      TZ: Europe/Rome
    ports:
      - 8310:8000
    volumes:
      - ./api:/app # cartella dell'applicazione
      - pki:/PKI
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
    networks:
      - cert-auth-net




  # web:
  #   container_name: simoweb
  #   image: nginx
  #   restart: unless-stopped
  #   ports:
  #     - 8210:80
  #   environment:
  #     MODE: DEVELOPMENT
  #     TZ: Europe/Rome
  #   links:
  #     - php
  #   depends_on:
  #     - php
  #     - api
  #   volumes:
  #     - ./web:/app # cartella del sito
  #     - ./assets:/app/assets # collegamento ai file statici
  #     - instagram_media:/app/assets/images/ig/download
  #     - ./config/nginx:/etc/nginx/conf.d
  #     # - /etc/timezone:/etc/timezone:ro
  #     # - /etc/localtime:/etc/localtime:ro
  #   networks:
  #     - simonet1

  # php:
  #   container_name: simophp
  #   image: php:8-fpm-bullseye
  #   volumes:
  #     - ./web:/app
  #     - instagram_media:/app/assets/images/ig/download
  #     - ./config/php/php.ini:/usr/local/etc/php/php.ini
  #     # - /etc/timezone:/etc/timezone:ro
  #     # - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     MODE: DEVELOPMENT
  #     TZ: Europe/Rome
  #   networks:
  #     - simonet1
